#!/usr/bin/env bash

function StartHomeAssistant {
  mkdir /config

  echo "Copy configuration.yaml"
  cp -f .devcontainer/configuration.yaml /config/ || echo ".devcontainer/configuration.yaml are missing!" exit 1

  # echo "Copy the custom component"
  rm -f /config/custom_components/myhomeserver1
  ln -f -s /workspaces/hass_myhomeserver1/custom_components/myhomeserver1 /config/custom_components/myhomeserver1

  echo "Start Home Assistant"
  hass -c /config
}

function InstallBrownpaperbagFromGit {
  pip install --upgrade git+git://github.com/bpaulin/brownpaperbag.git@master
}

function UpgradeHomeAssistantDev {
  python -m pip install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev
}

function SetHomeAssistantVersion {
  read -p 'Version: ' version
  python -m pip install --upgrade homeassistant==$version
}

function HomeAssistantConfigCheck {
  hass -c /config --script check_config
}
