name: validate

on:
  push:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Test
      run: |
        black --check .

    - uses: home-assistant/actions/hassfest@master
